### ISSUE TITLE
Segmentation fault - invalid memory reference RegCM4.9.6

### ISSUE THREAD

**Issue by Abdulhadi793** [ictp-esp/RegCM#12]
Hi. I have compiled the RegCM4.9.6 with gnu 6.3.0 and successfully complete the terrain and sst creation.However, to create the ICBC for CMIP6 historical period (MPI-ESM1-2-HR) is posing an error. 

 GLOBIDATE1 :  1950-02-01 00:00:00 UTC        
 GLOBIDATE2 :  2014-12-31 18:00:00 UTC        
 NSTEPS     :        94840
 Computing weights................... Done.
 Computing weights................... Done.
 Read in Static fields OK

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x2ACC6D1BDB97
#1  0x2ACC6D1BCD90
#2  0x2ACC6E99091F
#3  0x4674E9 in __mod_cmip6_MOD_get_cmip6
#4  0x46ADE9 in MAIN__ at icbc.F90:256 

 17604 Segmentation fault      (core dumped) ${RegCM_BIN}/icbc regcm.in

The forcing data is downloaded and placed on local disk. For the test case test_001 from the Testing directory is working fine. The issue is with the MPI-ESM1-2-HR. Your help is highly appreciated.

**Comment by mariefariprahman** [comment]
Hi Abdulhadi793, do you know where I can find and download the RegCM4.9.6 or newest RegCM version source code?

Thank you.

**Comment by meimeilll22** [comment]
Hi,have you solve this problem?
